/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CercleRouteImport } from './routes/cercle'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StablesIndexRouteImport } from './routes/stables.index'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as StablesIdRouteImport } from './routes/stables.$id'
import { Route as PackagesIdRouteImport } from './routes/packages.$id'
import { Route as CheckoutPackageIdRouteImport } from './routes/checkout.package.$id'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CercleRoute = CercleRouteImport.update({
  id: '/cercle',
  path: '/cercle',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StablesIndexRoute = StablesIndexRouteImport.update({
  id: '/stables/',
  path: '/stables/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const StablesIdRoute = StablesIdRouteImport.update({
  id: '/stables/$id',
  path: '/stables/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/packages/$id',
  path: '/packages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPackageIdRoute = CheckoutPackageIdRouteImport.update({
  id: '/checkout/package/$id',
  path: '/checkout/package/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/cercle': typeof CercleRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/training': typeof TrainingRoute
  '/packages/$id': typeof PackagesIdRoute
  '/stables/$id': typeof StablesIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/stables/': typeof StablesIndexRoute
  '/checkout/package/$id': typeof CheckoutPackageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/cercle': typeof CercleRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/training': typeof TrainingRoute
  '/packages/$id': typeof PackagesIdRoute
  '/stables/$id': typeof StablesIdRoute
  '/checkout': typeof CheckoutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/stables': typeof StablesIndexRoute
  '/checkout/package/$id': typeof CheckoutPackageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/cercle': typeof CercleRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/training': typeof TrainingRoute
  '/packages/$id': typeof PackagesIdRoute
  '/stables/$id': typeof StablesIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/stables/': typeof StablesIndexRoute
  '/checkout/package/$id': typeof CheckoutPackageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/cercle'
    | '/faq'
    | '/gallery'
    | '/reviews'
    | '/training'
    | '/packages/$id'
    | '/stables/$id'
    | '/checkout/'
    | '/dashboard/'
    | '/packages/'
    | '/stables/'
    | '/checkout/package/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/cercle'
    | '/faq'
    | '/gallery'
    | '/reviews'
    | '/training'
    | '/packages/$id'
    | '/stables/$id'
    | '/checkout'
    | '/dashboard'
    | '/packages'
    | '/stables'
    | '/checkout/package/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/cercle'
    | '/faq'
    | '/gallery'
    | '/reviews'
    | '/training'
    | '/packages/$id'
    | '/stables/$id'
    | '/checkout/'
    | '/dashboard/'
    | '/packages/'
    | '/stables/'
    | '/checkout/package/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  CercleRoute: typeof CercleRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  ReviewsRoute: typeof ReviewsRoute
  TrainingRoute: typeof TrainingRoute
  PackagesIdRoute: typeof PackagesIdRoute
  StablesIdRoute: typeof StablesIdRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  StablesIndexRoute: typeof StablesIndexRoute
  CheckoutPackageIdRoute: typeof CheckoutPackageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cercle': {
      id: '/cercle'
      path: '/cercle'
      fullPath: '/cercle'
      preLoaderRoute: typeof CercleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stables/': {
      id: '/stables/'
      path: '/stables'
      fullPath: '/stables/'
      preLoaderRoute: typeof StablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stables/$id': {
      id: '/stables/$id'
      path: '/stables/$id'
      fullPath: '/stables/$id'
      preLoaderRoute: typeof StablesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/packages/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/package/$id': {
      id: '/checkout/package/$id'
      path: '/checkout/package/$id'
      fullPath: '/checkout/package/$id'
      preLoaderRoute: typeof CheckoutPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  CercleRoute: CercleRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  ReviewsRoute: ReviewsRoute,
  TrainingRoute: TrainingRoute,
  PackagesIdRoute: PackagesIdRoute,
  StablesIdRoute: StablesIdRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  StablesIndexRoute: StablesIndexRoute,
  CheckoutPackageIdRoute: CheckoutPackageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
