/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CercleRouteImport } from './routes/cercle'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StablesIndexRouteImport } from './routes/stables.index'
import { Route as PackagesIndexRouteImport } from './routes/packages.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UsersIdRouteImport } from './routes/users.$id'
import { Route as StablesIdRouteImport } from './routes/stables.$id'
import { Route as SStableIdRouteImport } from './routes/s.$stableId'
import { Route as PackagesIdRouteImport } from './routes/packages.$id'
import { Route as DashboardRiderRouteImport } from './routes/dashboard.rider'
import { Route as DashboardLoyaltyRouteImport } from './routes/dashboard.loyalty'
import { Route as DashboardDriverRouteImport } from './routes/dashboard.driver'
import { Route as DashboardCxMediaRouteImport } from './routes/dashboard.cx-media'
import { Route as DashboardCaptainRouteImport } from './routes/dashboard.captain'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as AuthSwitchRouteImport } from './routes/auth.switch'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminHorsesRouteImport } from './routes/admin.horses'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as CheckoutPackageIdRouteImport } from './routes/checkout.package.$id'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CercleRoute = CercleRouteImport.update({
  id: '/cercle',
  path: '/cercle',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StablesIndexRoute = StablesIndexRouteImport.update({
  id: '/stables/',
  path: '/stables/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StablesIdRoute = StablesIdRouteImport.update({
  id: '/stables/$id',
  path: '/stables/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SStableIdRoute = SStableIdRouteImport.update({
  id: '/s/$stableId',
  path: '/s/$stableId',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesIdRoute = PackagesIdRouteImport.update({
  id: '/packages/$id',
  path: '/packages/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRiderRoute = DashboardRiderRouteImport.update({
  id: '/dashboard/rider',
  path: '/dashboard/rider',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLoyaltyRoute = DashboardLoyaltyRouteImport.update({
  id: '/dashboard/loyalty',
  path: '/dashboard/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDriverRoute = DashboardDriverRouteImport.update({
  id: '/dashboard/driver',
  path: '/dashboard/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCxMediaRoute = DashboardCxMediaRouteImport.update({
  id: '/dashboard/cx-media',
  path: '/dashboard/cx-media',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCaptainRoute = DashboardCaptainRouteImport.update({
  id: '/dashboard/captain',
  path: '/dashboard/captain',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSwitchRoute = AuthSwitchRouteImport.update({
  id: '/switch',
  path: '/switch',
  getParentRoute: () => AuthRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/admin/schedule',
  path: '/admin/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHorsesRoute = AdminHorsesRouteImport.update({
  id: '/admin/horses',
  path: '/admin/horses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutPackageIdRoute = CheckoutPackageIdRouteImport.update({
  id: '/checkout/package/$id',
  path: '/checkout/package/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/booking': typeof BookingRoute
  '/cercle': typeof CercleRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/horses': typeof AdminHorsesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/auth/switch': typeof AuthSwitchRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/captain': typeof DashboardCaptainRoute
  '/dashboard/cx-media': typeof DashboardCxMediaRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/loyalty': typeof DashboardLoyaltyRoute
  '/dashboard/rider': typeof DashboardRiderRoute
  '/packages/$id': typeof PackagesIdRoute
  '/s/$stableId': typeof SStableIdRoute
  '/stables/$id': typeof StablesIdRoute
  '/users/$id': typeof UsersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/stables/': typeof StablesIndexRoute
  '/checkout/package/$id': typeof CheckoutPackageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/booking': typeof BookingRoute
  '/cercle': typeof CercleRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/horses': typeof AdminHorsesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/auth/switch': typeof AuthSwitchRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/captain': typeof DashboardCaptainRoute
  '/dashboard/cx-media': typeof DashboardCxMediaRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/loyalty': typeof DashboardLoyaltyRoute
  '/dashboard/rider': typeof DashboardRiderRoute
  '/packages/$id': typeof PackagesIdRoute
  '/s/$stableId': typeof SStableIdRoute
  '/stables/$id': typeof StablesIdRoute
  '/users/$id': typeof UsersIdRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/stables': typeof StablesIndexRoute
  '/checkout/package/$id': typeof CheckoutPackageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/booking': typeof BookingRoute
  '/cercle': typeof CercleRoute
  '/chat': typeof ChatRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/horses': typeof AdminHorsesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/auth/switch': typeof AuthSwitchRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/captain': typeof DashboardCaptainRoute
  '/dashboard/cx-media': typeof DashboardCxMediaRoute
  '/dashboard/driver': typeof DashboardDriverRoute
  '/dashboard/loyalty': typeof DashboardLoyaltyRoute
  '/dashboard/rider': typeof DashboardRiderRoute
  '/packages/$id': typeof PackagesIdRoute
  '/s/$stableId': typeof SStableIdRoute
  '/stables/$id': typeof StablesIdRoute
  '/users/$id': typeof UsersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/stables/': typeof StablesIndexRoute
  '/checkout/package/$id': typeof CheckoutPackageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/cercle'
    | '/chat'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/leaderboard'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/reviews'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/training'
    | '/admin/analytics'
    | '/admin/horses'
    | '/admin/schedule'
    | '/auth/switch'
    | '/dashboard/admin'
    | '/dashboard/captain'
    | '/dashboard/cx-media'
    | '/dashboard/driver'
    | '/dashboard/loyalty'
    | '/dashboard/rider'
    | '/packages/$id'
    | '/s/$stableId'
    | '/stables/$id'
    | '/users/$id'
    | '/admin/'
    | '/checkout/'
    | '/dashboard/'
    | '/packages/'
    | '/stables/'
    | '/checkout/package/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/cercle'
    | '/chat'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/leaderboard'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/reviews'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/training'
    | '/admin/analytics'
    | '/admin/horses'
    | '/admin/schedule'
    | '/auth/switch'
    | '/dashboard/admin'
    | '/dashboard/captain'
    | '/dashboard/cx-media'
    | '/dashboard/driver'
    | '/dashboard/loyalty'
    | '/dashboard/rider'
    | '/packages/$id'
    | '/s/$stableId'
    | '/stables/$id'
    | '/users/$id'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/packages'
    | '/stables'
    | '/checkout/package/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/cercle'
    | '/chat'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/leaderboard'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/reviews'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/training'
    | '/admin/analytics'
    | '/admin/horses'
    | '/admin/schedule'
    | '/auth/switch'
    | '/dashboard/admin'
    | '/dashboard/captain'
    | '/dashboard/cx-media'
    | '/dashboard/driver'
    | '/dashboard/loyalty'
    | '/dashboard/rider'
    | '/packages/$id'
    | '/s/$stableId'
    | '/stables/$id'
    | '/users/$id'
    | '/admin/'
    | '/checkout/'
    | '/dashboard/'
    | '/packages/'
    | '/stables/'
    | '/checkout/package/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  BookingRoute: typeof BookingRoute
  CercleRoute: typeof CercleRoute
  ChatRoute: typeof ChatRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  TrainingRoute: typeof TrainingRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminHorsesRoute: typeof AdminHorsesRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardCaptainRoute: typeof DashboardCaptainRoute
  DashboardCxMediaRoute: typeof DashboardCxMediaRoute
  DashboardDriverRoute: typeof DashboardDriverRoute
  DashboardLoyaltyRoute: typeof DashboardLoyaltyRoute
  DashboardRiderRoute: typeof DashboardRiderRoute
  PackagesIdRoute: typeof PackagesIdRoute
  SStableIdRoute: typeof SStableIdRoute
  StablesIdRoute: typeof StablesIdRoute
  UsersIdRoute: typeof UsersIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PackagesIndexRoute: typeof PackagesIndexRoute
  StablesIndexRoute: typeof StablesIndexRoute
  CheckoutPackageIdRoute: typeof CheckoutPackageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cercle': {
      id: '/cercle'
      path: '/cercle'
      fullPath: '/cercle'
      preLoaderRoute: typeof CercleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stables/': {
      id: '/stables/'
      path: '/stables'
      fullPath: '/stables/'
      preLoaderRoute: typeof StablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/': {
      id: '/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stables/$id': {
      id: '/stables/$id'
      path: '/stables/$id'
      fullPath: '/stables/$id'
      preLoaderRoute: typeof StablesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$stableId': {
      id: '/s/$stableId'
      path: '/s/$stableId'
      fullPath: '/s/$stableId'
      preLoaderRoute: typeof SStableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages/$id': {
      id: '/packages/$id'
      path: '/packages/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof PackagesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/rider': {
      id: '/dashboard/rider'
      path: '/dashboard/rider'
      fullPath: '/dashboard/rider'
      preLoaderRoute: typeof DashboardRiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/loyalty': {
      id: '/dashboard/loyalty'
      path: '/dashboard/loyalty'
      fullPath: '/dashboard/loyalty'
      preLoaderRoute: typeof DashboardLoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/driver': {
      id: '/dashboard/driver'
      path: '/dashboard/driver'
      fullPath: '/dashboard/driver'
      preLoaderRoute: typeof DashboardDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cx-media': {
      id: '/dashboard/cx-media'
      path: '/dashboard/cx-media'
      fullPath: '/dashboard/cx-media'
      preLoaderRoute: typeof DashboardCxMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/captain': {
      id: '/dashboard/captain'
      path: '/dashboard/captain'
      fullPath: '/dashboard/captain'
      preLoaderRoute: typeof DashboardCaptainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/switch': {
      id: '/auth/switch'
      path: '/switch'
      fullPath: '/auth/switch'
      preLoaderRoute: typeof AuthSwitchRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/admin/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/horses': {
      id: '/admin/horses'
      path: '/admin/horses'
      fullPath: '/admin/horses'
      preLoaderRoute: typeof AdminHorsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/package/$id': {
      id: '/checkout/package/$id'
      path: '/checkout/package/$id'
      fullPath: '/checkout/package/$id'
      preLoaderRoute: typeof CheckoutPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSwitchRoute: typeof AuthSwitchRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSwitchRoute: AuthSwitchRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  BookingRoute: BookingRoute,
  CercleRoute: CercleRoute,
  ChatRoute: ChatRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  LeaderboardRoute: LeaderboardRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  TrainingRoute: TrainingRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminHorsesRoute: AdminHorsesRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardCaptainRoute: DashboardCaptainRoute,
  DashboardCxMediaRoute: DashboardCxMediaRoute,
  DashboardDriverRoute: DashboardDriverRoute,
  DashboardLoyaltyRoute: DashboardLoyaltyRoute,
  DashboardRiderRoute: DashboardRiderRoute,
  PackagesIdRoute: PackagesIdRoute,
  SStableIdRoute: SStableIdRoute,
  StablesIdRoute: StablesIdRoute,
  UsersIdRoute: UsersIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PackagesIndexRoute: PackagesIndexRoute,
  StablesIndexRoute: StablesIndexRoute,
  CheckoutPackageIdRoute: CheckoutPackageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
